### ISSUE TITLE
some problems about the code

### ISSUE THREAD

**Issue by FDYuan** [ChenTsuei/UMD#2]
Hi Cui, It is really great that you have released your code, it is really helpful to understand your paper UMD, there are some problems still bothers me.

1. test method with only one value return 
https://github.com/ChenTsuei/UMD/blob/4502c47ba4a033aad498a9fc8c9b6da6d16bd3d4/train.py#L306  
your code shows that the function `test` will return two values, but at 
https://github.com/ChenTsuei/UMD/blob/4502c47ba4a033aad498a9fc8c9b6da6d16bd3d4/test.py#L84 just return one value.

2. Image process problems
https://github.com/ChenTsuei/UMD/blob/4502c47ba4a033aad498a9fc8c9b6da6d16bd3d4/options/dataset_option.py#L84
In your code, you used `torchvision.transforms` API to process the image, and you have set the target image size to 64, but the original image is so large, it's width and height is about 400 to 600  pixel. `torchvision.Scale` may be used to scale the image to a small size, so much information of the image may lose without scale.

3. can you release the evaluation code
this item may same as the 1st one, it seems that you did not do an evaluation in the task of textual response generation. I have run your code and get a higher bleu score

looking forward to your answer.

**Comment by ChenTsuei** [comment]
@FDYuan Thanks for your questions.
1. The original idea was to compute the BLEU scores ourselves until we found the Perl script [mteval-v14.pl](https://github.com/moses-smt/mosesdecoder/blob/master/scripts/generic/mteval-v14.pl). But it needs a bit more involved to run this script, I'll provide the conversion script later. 
2. It might be a problem, but smaller images can reduce the number of parameters. I'd appreciate it if you could try different image sizes and see if there's any improvement.
3. As mentioned in the 1st item.

**Comment by ChenTsuei** [comment]
The README document and the conversion script is updated.
