### ISSUE TITLE
The detail about how to chose taxonomy path in prediction step

### ISSUE THREAD

**Issue by fandulu** [ChenTsuei/UMD#3]
Thanks for sharing this code, could I ask a question about detail in paper Fig 4. During training, the GT taxonomy path is known and can be directly used in MFB. During testing, there are many possible paths for the taxonomy tree, how to pick them for MFB? I have some difficulty to understand it and very appreciate if you can help.

**Comment by ChenTsuei** [comment]
Thanks for your question. The used taxonomies of products are external knowledge, which is still known in the evaluation procedure.

**Comment by fandulu** [comment]
Got it. Thanks.
