### ISSUE TITLE
File missing 'url2img.txt' 

### ISSUE THREAD

**Issue by Shandilya21** [ChenTsuei/UMD#4]
@ChenTsuei Thanks for publishing your code. As I going through the code, I find that in dataset_option.py, the "image2url.txt" text file is missing. this text file is neither in the MMD dataset nor with the images file that you shared in the drive. Is this file is generated through code?. If no, can you share this text file so that it is easy for me to proceed? 

Thanks 
Best

**Comment by ChenTsuei** [comment]
Thank you. The download link of url2img.txt has been updated.
